Rnjesus and an exampleGame
HarvardWestlake/Blocade pull request #11
Opened 2024-05-09 17:11 UTC by WilliamAbraham

2024-05-09 21:21 UTC, samskulsky submitted a review, later dismissed
The following test fails:
`FAILED tests/RNG/test_RNGV3exampleGame.py::test_play - assert 1 > 2`

But that is expected behavior for an example game. All other tests pass

2024-05-21 17:43 UTC, andrewtheiss requested changes
INFO     ape:provider.py:991 Confirmed 0x23973485e92e45737902d2333c931b87320984303341bb81989441a8a345f1b9 (total fees paid = 245668500000000)
INFO     ape:provider.py:991 Confirmed 0x23973485e92e45737902d2333c931b87320984303341bb81989441a8a345f1b9 (total fees paid = 245668500000000)
SUCCESS  ape:base.py:1392 Contract 'RNGV3' deployed to: 0x5FbDB2315678afecb367f032d93F642f64180aa3
INFO     ape:provider.py:991 Confirmed 0xe8dec200be8ca01b5b6462421f975cc41645f908ee499e0d541d603d34b4c82a (total fees paid = 308455281347171)
INFO     ape:provider.py:991 Confirmed 0xe8dec200be8ca01b5b6462421f975cc41645f908ee499e0d541d603d34b4c82a (total fees paid = 308455281347171)
SUCCESS  ape:base.py:1392 Contract 'RNGV3ExampleGame' deployed to: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
INFO     ape:provider.py:991 Confirmed 0x022c6631ab09a225f796e9cd3bc1695b422c3c4c328b3d936db59da33453d495 (total fees paid = 47495569474160)
INFO     ape:provider.py:991 Confirmed 0x022c6631ab09a225f796e9cd3bc1695b422c3c4c328b3d936db59da33453d495 (total fees paid = 47495569474160)
INFO     ape:provider.py:991 Confirmed 0xe2f233a8a011a73ebfc55d36d03e8ad0635baf7c8dac6e17ba7e50eaf547c0d3 (total fees paid = 14911711280452)
INFO     ape:provider.py:991 Confirmed 0xe2f233a8a011a73ebfc55d36d03e8ad0635baf7c8dac6e17ba7e50eaf547c0d3 (total fees paid = 14911711280452)
INFO     ape:provider.py:991 Confirmed 0xb35d382b459616040405f6907fd5049ed894ae296eae1114d3993c462c2c6266 (total fees paid = 9393502250748)
INFO     ape:provider.py:991 Confirmed 0xb35d382b459616040405f6907fd5049ed894ae296eae1114d3993c462c2c6266 (total fees paid = 9393502250748)
INFO     ape:provider.py:991 Confirmed 0x79c5290703992d7c1a5f9c0c5bd9bb378dce8ea85bc91d5da9134d4b0120afaa (total fees paid = 6464798307178)
INFO     ape:provider.py:991 Confirmed 0x79c5290703992d7c1a5f9c0c5bd9bb378dce8ea85bc91d5da9134d4b0120afaa (total fees paid = 6464798307178)
INFO     ape:provider.py:991 Confirmed 0x99b957b4c3bd6ff709d66db444d45be36c6420ba3851ba630afc99addfe39170 (total fees paid = 3230395372820)
INFO     ape:provider.py:991 Confirmed 0x99b957b4c3bd6ff709d66db444d45be36c6420ba3851ba630afc99addfe39170 (total fees paid = 3230395372820)
INFO     ape:provider.py:991 Confirmed 0xb8ea3f0a409afa152105cbeff7d723c182c17b0ba385e9a6d076ff03118dfa58 (total fees paid = 1894328276456)
INFO     ape:provider.py:991 Confirmed 0xb8ea3f0a409afa152105cbeff7d723c182c17b0ba385e9a6d076ff03118dfa58 (total fees paid = 1894328276456)
INFO     ape:provider.py:991 Confirmed 0x5b175117fdc7c4e40f9aee03bc694398b2542a00bda6e51dfc50c0254ec1a083 (total fees paid = 1110848435004)
INFO     ape:provider.py:991 Confirmed 0x5b175117fdc7c4e40f9aee03bc694398b2542a00bda6e51dfc50c0254ec1a083 (total fees paid = 1110848435004)
INFO     ape:provider.py:991 Confirmed 0x391f31b3cdbd8cdf3fe1fca3071b2066c4b4166eb46351d1db76430abab2a2c2 (total fees paid = 764508430668)
INFO     ape:provider.py:991 Confirmed 0x391f31b3cdbd8cdf3fe1fca3071b2066c4b4166eb46351d1db76430abab2a2c2 (total fees paid = 764508430668)
INFO     ape:provider.py:991 Confirmed 0x1c67dcfbc26b52ebc72d67a5be3eea80d51d7bbb96e14605b0aa68c4a1dbb090 (total fees paid = 448343540040)
INFO     ape:provider.py:991 Confirmed 0x1c67dcfbc26b52ebc72d67a5be3eea80d51d7bbb96e14605b0aa68c4a1dbb090 (total fees paid = 448343540040)
INFO     ape:provider.py:991 Confirmed 0xe4ac056560e685a28b2b581f14450f0a7b3c3976462b7a190eeea9553fef4694 (total fees paid = 262929662668)
INFO     ape:provider.py:991 Confirmed 0xe4ac056560e685a28b2b581f14450f0a7b3c3976462b7a190eeea9553fef4694 (total fees paid = 262929662668)
INFO     ape:provider.py:991 Confirmed 0xec0f0940eb7a23cb8c71da28558813ab0344c3ee1058a0c4e8242fcf953a4e88 (total fees paid = 129171062680)
INFO     ape:provider.py:991 Confirmed 0xec0f0940eb7a23cb8c71da28558813ab0344c3ee1058a0c4e8242fcf953a4e88 (total fees paid = 129171062680)
======================================================================= short test summary info ========================================================================
FAILED tests/RNG/test_RNGV3exampleGame.py::test_play - assert 1 > 2
===================================================================== 1 failed, 5 passed in 1.97s ======================================================================

make tests pass and fix log level output

2024-05-21 17:43 UTC, andrewtheiss commented on contracts/RNG/RNGV3.vy
> +#Deployed on Sepolia at: 0x1Cf23132e4797310A3897aB0e0367D861bdFA678
+1

2024-05-22 14:52 UTC, HarvardWestlake approved these changes

2024-05-22 14:53 UTC, andrewtheiss approved these changes

2024-05-22 14:53 UTC, merged