Signup
HarvardWestlake/Blocade pull request #4
Opened 2024-05-08 20:58 UTC by SarahB6

Created test for signup

2024-05-21 17:15 UTC, luke23571113 reviewed
Successfully runs test, and code looks good. 

============================================= test session starts =============================================
platform darwin -- Python 3.9.6, pytest-7.4.4, pluggy-1.4.0
rootdir: /Users/lukecollins/Documents/Topics/Blocade
plugins: eth-ape-0.7.22, web3-6.18.0
collected 5 items                                                                                             

tests/test_exampleGame.py ...                                                                           [ 60%]
tests/test_mintToken.py .                                                                               [ 80%]
tests/test_signupTester.py .                                                                            [100%]

============================================== 5 passed in 1.45s ==============================================

2024-05-22 17:39 UTC, andrewtheiss requested changes
Files are being changed and re-added / modified without the content of them effectively changing.  Please only update meaningful changes in files as this will mess up anyone who is changing these later.  

The work here (after fixing the requested changes) contains addition of a single setter and a variable.  After changes if it's accepted, this will be good for a B grade.

2024-05-22 17:39 UTC, andrewtheiss commented on tests/test_exampleGame.py
> -from ape import accounts, project
Why is this editing and re-adding the same file content?

2024-05-22 19:08 UTC, andrewtheiss requested changes

2024-05-22 19:08 UTC, andrewtheiss commented on contracts/Signup.vy
> +        # Wallet ID is already registered, raise an error
log not registered

2024-05-23 18:22 UTC, andrewtheiss approved these changes

2024-05-23 18:23 UTC, HarvardWestlake approved these changes
Working setter and getter

2024-05-23 18:23 UTC, merged